### ISSUE TITLE
Excel support

### ISSUE THREAD

**Issue by standage** [bioforensics/lusSTR#39]
Starting with version 2.0, the [`xlrd` Python package](https://github.com/python-excel/xlrd) will no longer support reading `.xlsx` files, only the legacy `.xls` files.

This doesn't require any immediate action—it may not require action for a long time, or ever. But if upgrading is necessary at some point, we'll have to decide whether to support reading `.xls` files and which library to use for `.xlsx` files. The [openpyxl package](https://openpyxl.readthedocs.io/) seems to be the recommended replacement.

**Comment by rnmitchell** [comment]
Closed with #41
